port: 8888
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    hard_wrap: false
    toc_levels: '1'
highlighter: rouge
gems: ['bourbon', 'neat']
exclude: [_drafts, Rakefile, node_modules, Gemfile, Gemfile.lock]

# TODO: this should be moved to _data
# Current RethinkDB version
version:
    major: "1.15"
    minor: 0
    codename: "Lawrence of Arabia"

sass:
    sass_dir: _sass

# Blog settings
paginate: 5
paginate_file: blog/index.html
paginate_path: /blog/page:num
permalink: /blog/:title
excerpt_separator: <!--more-->
