--- # Deployment config
# Connection details for a remote web server
web:
    host: teapot@rethinkdb.com
    port: 440
    directory: /srv/www/rethinkdb.com/public_html

# Connection details for Algolia
algolia:
    app_id: your_algolia_app_id
    api_key: your_algolia_api_key
